BASIC_AGENT_SPAWN_RATE = 0.01

BASE_REPLICATION_RATE = 0.04
BASE_MUTATION_RATE = 0.04
BASE_DEATH_RATE = 0.02

RANDOMNESS_FACTOR = 0.02

SPAWN, REPLICATE, MUTATE, DIE, NONE = "SPAWN", "REPLICATE", "MUTATE", "DIE", "NA"
AGENT, COUNT = "AGENT", "COUNT"

SIM_START_STATE = {
    0: {
        AGENT: {
            REPLICATE: BASE_REPLICATION_RATE,
            MUTATE: BASE_MUTATION_RATE,
            DIE: BASE_DEATH_RATE
        },
        COUNT: 0
    }
}